Simple ftp
Ususucsus/hw2 pull request #3
Opened 2020-10-02 15:42 UTC by Ususucsus

2020-10-05 17:31 UTC, yurii-litvinov requested changes
Юнит-тестов совсем нету.

2020-10-05 17:31 UTC, yurii-litvinov commented on SimpleFTP/Client/Program.cs
> +    public static class Program
Надо ещё комментарии

2020-10-05 17:31 UTC, yurii-litvinov commented on SimpleFTP/Client/Program.cs
> +            client.Close();
Вообще он объявлен как using var, так что сделает Close() сам. Хотя хуже не будет :)

2020-10-05 17:31 UTC, yurii-litvinov commented on SimpleFTP/Client/Program.cs
> +}
На самом деле, клиент тоже надо оформить как полноценный класс, с методами List и Get, и даже чтобы они возвращали что-то более разумное, чем строки. Иначе, например, тестировать клиентскую часть тяжело.

2020-10-05 17:31 UTC, yurii-litvinov commented on SimpleFTP/Server/Controller.cs
> +            if (inputData.Length == 0) return string.Empty;
Более принято
```csharp
if (inputData.Length == 0) 
{
    return string.Empty;
}
```

2020-10-05 17:31 UTC, yurii-litvinov commented on SimpleFTP/Server/Controller.cs
> +            var content = await File.ReadAllBytesAsync(path);
Если файл весит пару сотен гигабайт, это может быть плохой идеей

2020-10-05 17:31 UTC, yurii-litvinov commented on SimpleFTP/Server/Listener.cs
> +                    socket.Close();
Это лучше делать в finally, а вокруг всего остального написать try-catch. Потому что если что произойдёт, сокет останется незакрытым (а тут наверняка что-то произойдёт, это ж сеть)

2020-10-05 17:31 UTC, yurii-litvinov commented on SimpleFTP/Server/Responses/FileResponse.cs
> +        private bool IsDir { get; set; }
private-свойства? Для них нужны очень веские причины, почему это не поля

2020-10-05 17:31 UTC, yurii-litvinov commented on SimpleFTP/Server/Responses/ListCommandResponse.cs
> +        public override string ToString() => $"{this.Size} ({string.Join(") (", this.Files)})";
Скобки тут не нужны, в спецификации протокола это были метасимволы, ограничивающие фрагмент строки со звёздочкой

2020-10-19 13:44 UTC, yurii-litvinov requested changes
Ещё неплохо бы интеграционный тест иметь, где реальный клиент дёргал бы реальный сервер, чтобы доказать, что у них протокол одинаковый.

2020-10-19 13:44 UTC, yurii-litvinov commented on SimpleFTP/Client/FtpServer.cs
> +            for (var i = 0; i < filesSplit.Length; i+=2)
Пробелов не хватает

2020-10-19 13:44 UTC, yurii-litvinov commented on SimpleFTP/Client/FtpServer.cs
> +    public class FtpServer
Мм, клиент называется FtpServer, это не запутает пользователя?

2020-10-19 13:44 UTC, yurii-litvinov commented on SimpleFTP/Client/FtpServer.cs
> +            Console.WriteLine(length);
Не, не надо это на консоль выводить

2020-10-19 13:44 UTC, yurii-litvinov commented on SimpleFTP/Client/ListResponse.cs
> +        public int NumberOfFiles { get; }
А оно не равно всегда Files.Length?

2020-10-19 13:44 UTC, yurii-litvinov commented on SimpleFTP/Client/Program.cs
> +            Console.WriteLine("enter command");
Можно ещё хелп по командам печатать :)

2020-10-19 13:44 UTC, yurii-litvinov commented on SimpleFTP/Client/Program.cs
> +                    var file = File.Create(filePath);
using var

2020-10-19 13:44 UTC, yurii-litvinov commented on SimpleFTP/ClientTests/FtpServerTests.cs
> +                 result.Files[0].IsDirectory == false) ||
Не стоит сравниваться с булевыми константами. Так делают иногда, типа для читабельности, но вообще это бессмысленно. `== true`, например, тождественная операция для bool-ов

2020-10-19 13:44 UTC, yurii-litvinov commented on SimpleFTP/ClientTests/FtpServerTests.cs
> +    }
А Get?

2020-10-19 13:44 UTC, yurii-litvinov commented on SimpleFTP/ServerTests/ControllerTests/ControllerGetTests.cs
> +            file.Close();
Тоже лучше using var

2020-10-20 15:28 UTC, merged

2020-10-20 15:28 UTC, Ususucsus commented
9/10